package com.bitchat.android.onboarding

enum class OnboardingState {
    CHECKING,
    BLUETOOTH_CHECK,
    LOCATION_CHECK,
    BATTERY_OPTIMIZATION_CHECK,
    SPECIAL_PERMISSIONS_CHECK,
    DND_ACCESS_CHECK,
    PERMISSION_EXPLANATION,
    PERMISSION_REQUESTING,
    MODEL_SELECTION,
    INITIALIZING,
    COMPLETE,
    ERROR
}